//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v10.3.2+e7fae14
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>South Africa: Revealed</summary>
	[PublishedModel("southAfricaRevealed")]
	public partial class SouthAfricaRevealed : PublishedContentModel, ICurrency, IGeography, ISeason, ITheRainbowNation
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		public new const string ModelTypeAlias = "southAfricaRevealed";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<SouthAfricaRevealed, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public SouthAfricaRevealed(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Revealed Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("revealedImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RevealedImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "revealedImage");

		///<summary>
		/// Revealed Subtitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("revealedSubtitle")]
		public virtual string RevealedSubtitle => this.Value<string>(_publishedValueFallback, "revealedSubtitle");

		///<summary>
		/// Revealed Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("revealedTitle")]
		public virtual string RevealedTitle => this.Value<string>(_publishedValueFallback, "revealedTitle");

		///<summary>
		/// Currency Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("currencyDescription")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString CurrencyDescription => global::Umbraco.Cms.Web.Common.PublishedModels.Currency.GetCurrencyDescription(this, _publishedValueFallback);

		///<summary>
		/// Currency Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("currencyTitle")]
		public virtual string CurrencyTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Currency.GetCurrencyTitle(this, _publishedValueFallback);

		///<summary>
		/// Geography Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("geographyContent")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString GeographyContent => global::Umbraco.Cms.Web.Common.PublishedModels.Geography.GetGeographyContent(this, _publishedValueFallback);

		///<summary>
		/// Geography Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("geographyTitle")]
		public virtual string GeographyTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Geography.GetGeographyTitle(this, _publishedValueFallback);

		///<summary>
		/// Autumn Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("autumnContent")]
		public virtual string AutumnContent => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetAutumnContent(this, _publishedValueFallback);

		///<summary>
		/// Autumn Season
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("autumnSeason")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AutumnSeason => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetAutumnSeason(this, _publishedValueFallback);

		///<summary>
		/// Autumn Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("autumnTitle")]
		public virtual string AutumnTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetAutumnTitle(this, _publishedValueFallback);

		///<summary>
		/// Season Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seasonContent")]
		public virtual string SeasonContent => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetSeasonContent(this, _publishedValueFallback);

		///<summary>
		/// Season Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seasonTitle")]
		public virtual string SeasonTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetSeasonTitle(this, _publishedValueFallback);

		///<summary>
		/// Spring Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("springContent")]
		public virtual string SpringContent => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetSpringContent(this, _publishedValueFallback);

		///<summary>
		/// Spring Season
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("springSeason")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SpringSeason => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetSpringSeason(this, _publishedValueFallback);

		///<summary>
		/// Spring Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("springTitle")]
		public virtual string SpringTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetSpringTitle(this, _publishedValueFallback);

		///<summary>
		/// Summer Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("summerContent")]
		public virtual string SummerContent => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetSummerContent(this, _publishedValueFallback);

		///<summary>
		/// SummerSeason
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("summerSeason")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SummerSeason => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetSummerSeason(this, _publishedValueFallback);

		///<summary>
		/// Summer Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("summerTitle")]
		public virtual string SummerTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetSummerTitle(this, _publishedValueFallback);

		///<summary>
		/// Winter Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("winterContent")]
		public virtual string WinterContent => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetWinterContent(this, _publishedValueFallback);

		///<summary>
		/// Winter Season
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("winterSeason")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops WinterSeason => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetWinterSeason(this, _publishedValueFallback);

		///<summary>
		/// Winter Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("winterTitle")]
		public virtual string WinterTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Season.GetWinterTitle(this, _publishedValueFallback);

		///<summary>
		/// Fifth Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fifthImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FifthImage => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetFifthImage(this, _publishedValueFallback);

		///<summary>
		/// Fifth Image Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fifthImageTitle")]
		public virtual string FifthImageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetFifthImageTitle(this, _publishedValueFallback);

		///<summary>
		/// First Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firstImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FirstImage => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetFirstImage(this, _publishedValueFallback);

		///<summary>
		/// First Image Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firstImageTitle")]
		public virtual string FirstImageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetFirstImageTitle(this, _publishedValueFallback);

		///<summary>
		/// Fourth Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fourthImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FourthImage => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetFourthImage(this, _publishedValueFallback);

		///<summary>
		/// Fourth Image Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fourthImageTitle")]
		public virtual string FourthImageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetFourthImageTitle(this, _publishedValueFallback);

		///<summary>
		/// Rainbow Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rainbowContent")]
		public virtual string RainbowContent => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetRainbowContent(this, _publishedValueFallback);

		///<summary>
		/// Rainbow Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rainbowTitle")]
		public virtual string RainbowTitle => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetRainbowTitle(this, _publishedValueFallback);

		///<summary>
		/// Second Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("secondImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SecondImage => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetSecondImage(this, _publishedValueFallback);

		///<summary>
		/// Second Image Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("secondImageTitle")]
		public virtual string SecondImageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetSecondImageTitle(this, _publishedValueFallback);

		///<summary>
		/// Third Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("thirdImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ThirdImage => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetThirdImage(this, _publishedValueFallback);

		///<summary>
		/// Third Image Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.3.2+e7fae14")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("thirdImageTitle")]
		public virtual string ThirdImageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.TheRainbowNation.GetThirdImageTitle(this, _publishedValueFallback);
	}
}
